// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCd9vL3Zn6tWY6-t6cFGVcz2qmPgOEL_V4',
    appId: '1:287585132101:web:edcfef60aba3e1147dcd2c',
    messagingSenderId: '287585132101',
    projectId: 'gamecritix-75af7',
    authDomain: 'gamecritix-75af7.firebaseapp.com',
    storageBucket: 'gamecritix-75af7.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCWHMmSE9FAve8HGsBvAZO-jLf-YBtuF78',
    appId: '1:287585132101:android:bf73b0540de0f6037dcd2c',
    messagingSenderId: '287585132101',
    projectId: 'gamecritix-75af7',
    storageBucket: 'gamecritix-75af7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4_-ixybjFR6SvnFS0PiKW-7Zv-9mv7cw',
    appId: '1:287585132101:ios:ffa41880d6f7ba5e7dcd2c',
    messagingSenderId: '287585132101',
    projectId: 'gamecritix-75af7',
    storageBucket: 'gamecritix-75af7.firebasestorage.app',
    iosBundleId: 'com.example.gameCritix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4_-ixybjFR6SvnFS0PiKW-7Zv-9mv7cw',
    appId: '1:287585132101:ios:ffa41880d6f7ba5e7dcd2c',
    messagingSenderId: '287585132101',
    projectId: 'gamecritix-75af7',
    storageBucket: 'gamecritix-75af7.firebasestorage.app',
    iosBundleId: 'com.example.gameCritix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCd9vL3Zn6tWY6-t6cFGVcz2qmPgOEL_V4',
    appId: '1:287585132101:web:a6ad2de1bf4150ef7dcd2c',
    messagingSenderId: '287585132101',
    projectId: 'gamecritix-75af7',
    authDomain: 'gamecritix-75af7.firebaseapp.com',
    storageBucket: 'gamecritix-75af7.firebasestorage.app',
  );

}